group: demo
name: demo
load: 

image_size: [512,512]
input_size: [256,256]
gpu: 0
output_root: output
seed: 0
test_input_frames: 8
proj_main_cam: true
use_mask: true
save_video: true
save_frames: false
fovy: 30.00000115370317
image_data: false
single_input: false
crm: true
save_per_view_ply: false
lucid_cam: true
model_key: pretrained/sd-2-1-base
ckpt:
yaml:
save_path:



pretrain:
    depth:

arch:
    svd: false

data:
    num_workers: 6
    bgcolor: 1
    demo_path:

rendering:
    zfar: 2.5
    znear: 0.5

optim:
    lr: 3.e-5
    weight_decay: 0.05
    clip_norm: 
    amp: false 
    accum: 1
    sched: false
    fix_dpt: false

freq:
    print: 200
    print_eval: 100
    scalar: 1000 # iterations
    vis: 1000 # iterations
    save_vis: 1000
    ckpt_latest: 1000 # iterations
    eval: 1

    


